// Code generated by go-swagger; DO NOT EDIT.

package screens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewScreensListParams creates a new ScreensListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewScreensListParams() *ScreensListParams {
	return &ScreensListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewScreensListParamsWithTimeout creates a new ScreensListParams object
// with the ability to set a timeout on a request.
func NewScreensListParamsWithTimeout(timeout time.Duration) *ScreensListParams {
	return &ScreensListParams{
		timeout: timeout,
	}
}

// NewScreensListParamsWithContext creates a new ScreensListParams object
// with the ability to set a context for a request.
func NewScreensListParamsWithContext(ctx context.Context) *ScreensListParams {
	return &ScreensListParams{
		Context: ctx,
	}
}

// NewScreensListParamsWithHTTPClient creates a new ScreensListParams object
// with the ability to set a custom HTTPClient for a request.
func NewScreensListParamsWithHTTPClient(client *http.Client) *ScreensListParams {
	return &ScreensListParams{
		HTTPClient: client,
	}
}

/* ScreensListParams contains all the parameters to send to the API endpoint
   for the screens list operation.

   Typically these are written to a http.Request.
*/
type ScreensListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the screens list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScreensListParams) WithDefaults() *ScreensListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the screens list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScreensListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the screens list params
func (o *ScreensListParams) WithTimeout(timeout time.Duration) *ScreensListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the screens list params
func (o *ScreensListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the screens list params
func (o *ScreensListParams) WithContext(ctx context.Context) *ScreensListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the screens list params
func (o *ScreensListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the screens list params
func (o *ScreensListParams) WithHTTPClient(client *http.Client) *ScreensListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the screens list params
func (o *ScreensListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ScreensListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
