// Code generated by go-swagger; DO NOT EDIT.

package screens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// ScreensCreateReader is a Reader for the ScreensCreate structure.
type ScreensCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScreensCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewScreensCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewScreensCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewScreensCreateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewScreensCreateCreated creates a ScreensCreateCreated with default headers values
func NewScreensCreateCreated() *ScreensCreateCreated {
	return &ScreensCreateCreated{}
}

/* ScreensCreateCreated describes a response with status code 201, with default header values.

ScreensCreateCreated screens create created
*/
type ScreensCreateCreated struct {
	Payload *models.ScreenDetailed
}

func (o *ScreensCreateCreated) Error() string {
	return fmt.Sprintf("[POST /screens/][%d] screensCreateCreated  %+v", 201, o.Payload)
}
func (o *ScreensCreateCreated) GetPayload() *models.ScreenDetailed {
	return o.Payload
}

func (o *ScreensCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ScreenDetailed)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewScreensCreateBadRequest creates a ScreensCreateBadRequest with default headers values
func NewScreensCreateBadRequest() *ScreensCreateBadRequest {
	return &ScreensCreateBadRequest{}
}

/* ScreensCreateBadRequest describes a response with status code 400, with default header values.

You sent a malformed or bad request.
*/
type ScreensCreateBadRequest struct {
}

func (o *ScreensCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /screens/][%d] screensCreateBadRequest ", 400)
}

func (o *ScreensCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewScreensCreateUnauthorized creates a ScreensCreateUnauthorized with default headers values
func NewScreensCreateUnauthorized() *ScreensCreateUnauthorized {
	return &ScreensCreateUnauthorized{}
}

/* ScreensCreateUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type ScreensCreateUnauthorized struct {
}

func (o *ScreensCreateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /screens/][%d] screensCreateUnauthorized ", 401)
}

func (o *ScreensCreateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
