// Code generated by go-swagger; DO NOT EDIT.

package screens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// NewScreensCreateParams creates a new ScreensCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewScreensCreateParams() *ScreensCreateParams {
	return &ScreensCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewScreensCreateParamsWithTimeout creates a new ScreensCreateParams object
// with the ability to set a timeout on a request.
func NewScreensCreateParamsWithTimeout(timeout time.Duration) *ScreensCreateParams {
	return &ScreensCreateParams{
		timeout: timeout,
	}
}

// NewScreensCreateParamsWithContext creates a new ScreensCreateParams object
// with the ability to set a context for a request.
func NewScreensCreateParamsWithContext(ctx context.Context) *ScreensCreateParams {
	return &ScreensCreateParams{
		Context: ctx,
	}
}

// NewScreensCreateParamsWithHTTPClient creates a new ScreensCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewScreensCreateParamsWithHTTPClient(client *http.Client) *ScreensCreateParams {
	return &ScreensCreateParams{
		HTTPClient: client,
	}
}

/* ScreensCreateParams contains all the parameters to send to the API endpoint
   for the screens create operation.

   Typically these are written to a http.Request.
*/
type ScreensCreateParams struct {

	// Data.
	Data *models.ScreenCreate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the screens create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScreensCreateParams) WithDefaults() *ScreensCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the screens create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScreensCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the screens create params
func (o *ScreensCreateParams) WithTimeout(timeout time.Duration) *ScreensCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the screens create params
func (o *ScreensCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the screens create params
func (o *ScreensCreateParams) WithContext(ctx context.Context) *ScreensCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the screens create params
func (o *ScreensCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the screens create params
func (o *ScreensCreateParams) WithHTTPClient(client *http.Client) *ScreensCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the screens create params
func (o *ScreensCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the screens create params
func (o *ScreensCreateParams) WithData(data *models.ScreenCreate) *ScreensCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the screens create params
func (o *ScreensCreateParams) SetData(data *models.ScreenCreate) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *ScreensCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
