// Code generated by go-swagger; DO NOT EDIT.

package screens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// ScreensDeleteReader is a Reader for the ScreensDelete structure.
type ScreensDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScreensDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewScreensDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewScreensDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewScreensDeleteOK creates a ScreensDeleteOK with default headers values
func NewScreensDeleteOK() *ScreensDeleteOK {
	return &ScreensDeleteOK{}
}

/* ScreensDeleteOK describes a response with status code 200, with default header values.

ScreensDeleteOK screens delete o k
*/
type ScreensDeleteOK struct {
}

func (o *ScreensDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /screens/{id}/][%d] screensDeleteOK ", 200)
}

func (o *ScreensDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewScreensDeleteUnauthorized creates a ScreensDeleteUnauthorized with default headers values
func NewScreensDeleteUnauthorized() *ScreensDeleteUnauthorized {
	return &ScreensDeleteUnauthorized{}
}

/* ScreensDeleteUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type ScreensDeleteUnauthorized struct {
}

func (o *ScreensDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /screens/{id}/][%d] screensDeleteUnauthorized ", 401)
}

func (o *ScreensDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
