// Code generated by go-swagger; DO NOT EDIT.

package screens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// ScreensListReader is a Reader for the ScreensList structure.
type ScreensListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScreensListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewScreensListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewScreensListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewScreensListOK creates a ScreensListOK with default headers values
func NewScreensListOK() *ScreensListOK {
	return &ScreensListOK{}
}

/* ScreensListOK describes a response with status code 200, with default header values.

ScreensListOK screens list o k
*/
type ScreensListOK struct {
	Payload *models.ScreenEndpoint
}

func (o *ScreensListOK) Error() string {
	return fmt.Sprintf("[GET /screens/][%d] screensListOK  %+v", 200, o.Payload)
}
func (o *ScreensListOK) GetPayload() *models.ScreenEndpoint {
	return o.Payload
}

func (o *ScreensListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ScreenEndpoint)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewScreensListUnauthorized creates a ScreensListUnauthorized with default headers values
func NewScreensListUnauthorized() *ScreensListUnauthorized {
	return &ScreensListUnauthorized{}
}

/* ScreensListUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type ScreensListUnauthorized struct {
}

func (o *ScreensListUnauthorized) Error() string {
	return fmt.Sprintf("[GET /screens/][%d] screensListUnauthorized ", 401)
}

func (o *ScreensListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
