// Code generated by go-swagger; DO NOT EDIT.

package screens

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// ScreensUploadReader is a Reader for the ScreensUpload structure.
type ScreensUploadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ScreensUploadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewScreensUploadCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewScreensUploadCreated creates a ScreensUploadCreated with default headers values
func NewScreensUploadCreated() *ScreensUploadCreated {
	return &ScreensUploadCreated{}
}

/* ScreensUploadCreated describes a response with status code 201, with default header values.

ScreensUploadCreated screens upload created
*/
type ScreensUploadCreated struct {
	Payload *models.ScreenCreate
}

func (o *ScreensUploadCreated) Error() string {
	return fmt.Sprintf("[POST /screens/upload/][%d] screensUploadCreated  %+v", 201, o.Payload)
}
func (o *ScreensUploadCreated) GetPayload() *models.ScreenCreate {
	return o.Payload
}

func (o *ScreensUploadCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ScreenCreate)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
