// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ScreenCreate screen create
//
// swagger:model ScreenCreate
type ScreenCreate struct {

	// Name
	//
	// Name of the new screen
	// Min Length: 1
	Name string `json:"name,omitempty"`

	// Pin
	//
	// Pin code created with registrations endpoint
	// Required: true
	// Min Length: 1
	Pin *string `json:"pin"`
}

// Validate validates this screen create
func (m *ScreenCreate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePin(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ScreenCreate) validateName(formats strfmt.Registry) error {
	if swag.IsZero(m.Name) { // not required
		return nil
	}

	if err := validate.MinLength("name", "body", m.Name, 1); err != nil {
		return err
	}

	return nil
}

func (m *ScreenCreate) validatePin(formats strfmt.Registry) error {

	if err := validate.Required("pin", "body", m.Pin); err != nil {
		return err
	}

	if err := validate.MinLength("pin", "body", *m.Pin, 1); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this screen create based on context it is used
func (m *ScreenCreate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ScreenCreate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ScreenCreate) UnmarshalBinary(b []byte) error {
	var res ScreenCreate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
