// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// AssetsCreateReader is a Reader for the AssetsCreate structure.
type AssetsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AssetsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewAssetsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAssetsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAssetsCreateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAssetsCreateCreated creates a AssetsCreateCreated with default headers values
func NewAssetsCreateCreated() *AssetsCreateCreated {
	return &AssetsCreateCreated{}
}

/* AssetsCreateCreated describes a response with status code 201, with default header values.

AssetsCreateCreated assets create created
*/
type AssetsCreateCreated struct {
	Payload *models.Asset
}

func (o *AssetsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /assets/][%d] assetsCreateCreated  %+v", 201, o.Payload)
}
func (o *AssetsCreateCreated) GetPayload() *models.Asset {
	return o.Payload
}

func (o *AssetsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Asset)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAssetsCreateBadRequest creates a AssetsCreateBadRequest with default headers values
func NewAssetsCreateBadRequest() *AssetsCreateBadRequest {
	return &AssetsCreateBadRequest{}
}

/* AssetsCreateBadRequest describes a response with status code 400, with default header values.

You sent a malformed or bad request.
*/
type AssetsCreateBadRequest struct {
}

func (o *AssetsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /assets/][%d] assetsCreateBadRequest ", 400)
}

func (o *AssetsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAssetsCreateUnauthorized creates a AssetsCreateUnauthorized with default headers values
func NewAssetsCreateUnauthorized() *AssetsCreateUnauthorized {
	return &AssetsCreateUnauthorized{}
}

/* AssetsCreateUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type AssetsCreateUnauthorized struct {
}

func (o *AssetsCreateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /assets/][%d] assetsCreateUnauthorized ", 401)
}

func (o *AssetsCreateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
