// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAssetsDeleteParams creates a new AssetsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAssetsDeleteParams() *AssetsDeleteParams {
	return &AssetsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAssetsDeleteParamsWithTimeout creates a new AssetsDeleteParams object
// with the ability to set a timeout on a request.
func NewAssetsDeleteParamsWithTimeout(timeout time.Duration) *AssetsDeleteParams {
	return &AssetsDeleteParams{
		timeout: timeout,
	}
}

// NewAssetsDeleteParamsWithContext creates a new AssetsDeleteParams object
// with the ability to set a context for a request.
func NewAssetsDeleteParamsWithContext(ctx context.Context) *AssetsDeleteParams {
	return &AssetsDeleteParams{
		Context: ctx,
	}
}

// NewAssetsDeleteParamsWithHTTPClient creates a new AssetsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewAssetsDeleteParamsWithHTTPClient(client *http.Client) *AssetsDeleteParams {
	return &AssetsDeleteParams{
		HTTPClient: client,
	}
}

/* AssetsDeleteParams contains all the parameters to send to the API endpoint
   for the assets delete operation.

   Typically these are written to a http.Request.
*/
type AssetsDeleteParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the assets delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetsDeleteParams) WithDefaults() *AssetsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the assets delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the assets delete params
func (o *AssetsDeleteParams) WithTimeout(timeout time.Duration) *AssetsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the assets delete params
func (o *AssetsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the assets delete params
func (o *AssetsDeleteParams) WithContext(ctx context.Context) *AssetsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the assets delete params
func (o *AssetsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the assets delete params
func (o *AssetsDeleteParams) WithHTTPClient(client *http.Client) *AssetsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the assets delete params
func (o *AssetsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the assets delete params
func (o *AssetsDeleteParams) WithID(id string) *AssetsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the assets delete params
func (o *AssetsDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *AssetsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
