// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAssetsListParams creates a new AssetsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAssetsListParams() *AssetsListParams {
	return &AssetsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAssetsListParamsWithTimeout creates a new AssetsListParams object
// with the ability to set a timeout on a request.
func NewAssetsListParamsWithTimeout(timeout time.Duration) *AssetsListParams {
	return &AssetsListParams{
		timeout: timeout,
	}
}

// NewAssetsListParamsWithContext creates a new AssetsListParams object
// with the ability to set a context for a request.
func NewAssetsListParamsWithContext(ctx context.Context) *AssetsListParams {
	return &AssetsListParams{
		Context: ctx,
	}
}

// NewAssetsListParamsWithHTTPClient creates a new AssetsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewAssetsListParamsWithHTTPClient(client *http.Client) *AssetsListParams {
	return &AssetsListParams{
		HTTPClient: client,
	}
}

/* AssetsListParams contains all the parameters to send to the API endpoint
   for the assets list operation.

   Typically these are written to a http.Request.
*/
type AssetsListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the assets list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetsListParams) WithDefaults() *AssetsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the assets list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the assets list params
func (o *AssetsListParams) WithTimeout(timeout time.Duration) *AssetsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the assets list params
func (o *AssetsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the assets list params
func (o *AssetsListParams) WithContext(ctx context.Context) *AssetsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the assets list params
func (o *AssetsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the assets list params
func (o *AssetsListParams) WithHTTPClient(client *http.Client) *AssetsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the assets list params
func (o *AssetsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AssetsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
