// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAssetsReadParams creates a new AssetsReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAssetsReadParams() *AssetsReadParams {
	return &AssetsReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAssetsReadParamsWithTimeout creates a new AssetsReadParams object
// with the ability to set a timeout on a request.
func NewAssetsReadParamsWithTimeout(timeout time.Duration) *AssetsReadParams {
	return &AssetsReadParams{
		timeout: timeout,
	}
}

// NewAssetsReadParamsWithContext creates a new AssetsReadParams object
// with the ability to set a context for a request.
func NewAssetsReadParamsWithContext(ctx context.Context) *AssetsReadParams {
	return &AssetsReadParams{
		Context: ctx,
	}
}

// NewAssetsReadParamsWithHTTPClient creates a new AssetsReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewAssetsReadParamsWithHTTPClient(client *http.Client) *AssetsReadParams {
	return &AssetsReadParams{
		HTTPClient: client,
	}
}

/* AssetsReadParams contains all the parameters to send to the API endpoint
   for the assets read operation.

   Typically these are written to a http.Request.
*/
type AssetsReadParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the assets read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetsReadParams) WithDefaults() *AssetsReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the assets read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetsReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the assets read params
func (o *AssetsReadParams) WithTimeout(timeout time.Duration) *AssetsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the assets read params
func (o *AssetsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the assets read params
func (o *AssetsReadParams) WithContext(ctx context.Context) *AssetsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the assets read params
func (o *AssetsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the assets read params
func (o *AssetsReadParams) WithHTTPClient(client *http.Client) *AssetsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the assets read params
func (o *AssetsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the assets read params
func (o *AssetsReadParams) WithID(id string) *AssetsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the assets read params
func (o *AssetsReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *AssetsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
