// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// AssetsUpdateReader is a Reader for the AssetsUpdate structure.
type AssetsUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AssetsUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAssetsUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAssetsUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAssetsUpdateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAssetsUpdateOK creates a AssetsUpdateOK with default headers values
func NewAssetsUpdateOK() *AssetsUpdateOK {
	return &AssetsUpdateOK{}
}

/* AssetsUpdateOK describes a response with status code 200, with default header values.

AssetsUpdateOK assets update o k
*/
type AssetsUpdateOK struct {
	Payload *models.Asset
}

func (o *AssetsUpdateOK) Error() string {
	return fmt.Sprintf("[PUT /assets/{id}/][%d] assetsUpdateOK  %+v", 200, o.Payload)
}
func (o *AssetsUpdateOK) GetPayload() *models.Asset {
	return o.Payload
}

func (o *AssetsUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Asset)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAssetsUpdateBadRequest creates a AssetsUpdateBadRequest with default headers values
func NewAssetsUpdateBadRequest() *AssetsUpdateBadRequest {
	return &AssetsUpdateBadRequest{}
}

/* AssetsUpdateBadRequest describes a response with status code 400, with default header values.

You sent a malformed or bad request.
*/
type AssetsUpdateBadRequest struct {
}

func (o *AssetsUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PUT /assets/{id}/][%d] assetsUpdateBadRequest ", 400)
}

func (o *AssetsUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAssetsUpdateUnauthorized creates a AssetsUpdateUnauthorized with default headers values
func NewAssetsUpdateUnauthorized() *AssetsUpdateUnauthorized {
	return &AssetsUpdateUnauthorized{}
}

/* AssetsUpdateUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type AssetsUpdateUnauthorized struct {
}

func (o *AssetsUpdateUnauthorized) Error() string {
	return fmt.Sprintf("[PUT /assets/{id}/][%d] assetsUpdateUnauthorized ", 401)
}

func (o *AssetsUpdateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
