// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// NewAssetsPartialUpdateParams creates a new AssetsPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAssetsPartialUpdateParams() *AssetsPartialUpdateParams {
	return &AssetsPartialUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAssetsPartialUpdateParamsWithTimeout creates a new AssetsPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewAssetsPartialUpdateParamsWithTimeout(timeout time.Duration) *AssetsPartialUpdateParams {
	return &AssetsPartialUpdateParams{
		timeout: timeout,
	}
}

// NewAssetsPartialUpdateParamsWithContext creates a new AssetsPartialUpdateParams object
// with the ability to set a context for a request.
func NewAssetsPartialUpdateParamsWithContext(ctx context.Context) *AssetsPartialUpdateParams {
	return &AssetsPartialUpdateParams{
		Context: ctx,
	}
}

// NewAssetsPartialUpdateParamsWithHTTPClient creates a new AssetsPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewAssetsPartialUpdateParamsWithHTTPClient(client *http.Client) *AssetsPartialUpdateParams {
	return &AssetsPartialUpdateParams{
		HTTPClient: client,
	}
}

/* AssetsPartialUpdateParams contains all the parameters to send to the API endpoint
   for the assets partial update operation.

   Typically these are written to a http.Request.
*/
type AssetsPartialUpdateParams struct {

	// Data.
	Data *models.AssetUpdate

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the assets partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetsPartialUpdateParams) WithDefaults() *AssetsPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the assets partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetsPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the assets partial update params
func (o *AssetsPartialUpdateParams) WithTimeout(timeout time.Duration) *AssetsPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the assets partial update params
func (o *AssetsPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the assets partial update params
func (o *AssetsPartialUpdateParams) WithContext(ctx context.Context) *AssetsPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the assets partial update params
func (o *AssetsPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the assets partial update params
func (o *AssetsPartialUpdateParams) WithHTTPClient(client *http.Client) *AssetsPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the assets partial update params
func (o *AssetsPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the assets partial update params
func (o *AssetsPartialUpdateParams) WithData(data *models.AssetUpdate) *AssetsPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the assets partial update params
func (o *AssetsPartialUpdateParams) SetData(data *models.AssetUpdate) {
	o.Data = data
}

// WithID adds the id to the assets partial update params
func (o *AssetsPartialUpdateParams) WithID(id string) *AssetsPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the assets partial update params
func (o *AssetsPartialUpdateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *AssetsPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
