// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// AssetsPartialUpdateReader is a Reader for the AssetsPartialUpdate structure.
type AssetsPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AssetsPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAssetsPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewAssetsPartialUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewAssetsPartialUpdateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAssetsPartialUpdateOK creates a AssetsPartialUpdateOK with default headers values
func NewAssetsPartialUpdateOK() *AssetsPartialUpdateOK {
	return &AssetsPartialUpdateOK{}
}

/* AssetsPartialUpdateOK describes a response with status code 200, with default header values.

AssetsPartialUpdateOK assets partial update o k
*/
type AssetsPartialUpdateOK struct {
	Payload *models.Asset
}

func (o *AssetsPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /assets/{id}/][%d] assetsPartialUpdateOK  %+v", 200, o.Payload)
}
func (o *AssetsPartialUpdateOK) GetPayload() *models.Asset {
	return o.Payload
}

func (o *AssetsPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Asset)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewAssetsPartialUpdateBadRequest creates a AssetsPartialUpdateBadRequest with default headers values
func NewAssetsPartialUpdateBadRequest() *AssetsPartialUpdateBadRequest {
	return &AssetsPartialUpdateBadRequest{}
}

/* AssetsPartialUpdateBadRequest describes a response with status code 400, with default header values.

You sent a malformed or bad request.
*/
type AssetsPartialUpdateBadRequest struct {
}

func (o *AssetsPartialUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /assets/{id}/][%d] assetsPartialUpdateBadRequest ", 400)
}

func (o *AssetsPartialUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAssetsPartialUpdateUnauthorized creates a AssetsPartialUpdateUnauthorized with default headers values
func NewAssetsPartialUpdateUnauthorized() *AssetsPartialUpdateUnauthorized {
	return &AssetsPartialUpdateUnauthorized{}
}

/* AssetsPartialUpdateUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type AssetsPartialUpdateUnauthorized struct {
}

func (o *AssetsPartialUpdateUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /assets/{id}/][%d] assetsPartialUpdateUnauthorized ", 401)
}

func (o *AssetsPartialUpdateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
