// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// NewAssetsUpdateParams creates a new AssetsUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAssetsUpdateParams() *AssetsUpdateParams {
	return &AssetsUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAssetsUpdateParamsWithTimeout creates a new AssetsUpdateParams object
// with the ability to set a timeout on a request.
func NewAssetsUpdateParamsWithTimeout(timeout time.Duration) *AssetsUpdateParams {
	return &AssetsUpdateParams{
		timeout: timeout,
	}
}

// NewAssetsUpdateParamsWithContext creates a new AssetsUpdateParams object
// with the ability to set a context for a request.
func NewAssetsUpdateParamsWithContext(ctx context.Context) *AssetsUpdateParams {
	return &AssetsUpdateParams{
		Context: ctx,
	}
}

// NewAssetsUpdateParamsWithHTTPClient creates a new AssetsUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewAssetsUpdateParamsWithHTTPClient(client *http.Client) *AssetsUpdateParams {
	return &AssetsUpdateParams{
		HTTPClient: client,
	}
}

/* AssetsUpdateParams contains all the parameters to send to the API endpoint
   for the assets update operation.

   Typically these are written to a http.Request.
*/
type AssetsUpdateParams struct {

	// Data.
	Data *models.AssetUpdate

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the assets update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetsUpdateParams) WithDefaults() *AssetsUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the assets update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AssetsUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the assets update params
func (o *AssetsUpdateParams) WithTimeout(timeout time.Duration) *AssetsUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the assets update params
func (o *AssetsUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the assets update params
func (o *AssetsUpdateParams) WithContext(ctx context.Context) *AssetsUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the assets update params
func (o *AssetsUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the assets update params
func (o *AssetsUpdateParams) WithHTTPClient(client *http.Client) *AssetsUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the assets update params
func (o *AssetsUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the assets update params
func (o *AssetsUpdateParams) WithData(data *models.AssetUpdate) *AssetsUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the assets update params
func (o *AssetsUpdateParams) SetData(data *models.AssetUpdate) {
	o.Data = data
}

// WithID adds the id to the assets update params
func (o *AssetsUpdateParams) WithID(id string) *AssetsUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the assets update params
func (o *AssetsUpdateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *AssetsUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
