// Code generated by go-swagger; DO NOT EDIT.

package assets

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// AssetsDeleteReader is a Reader for the AssetsDelete structure.
type AssetsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *AssetsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewAssetsDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewAssetsDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewAssetsDeleteOK creates a AssetsDeleteOK with default headers values
func NewAssetsDeleteOK() *AssetsDeleteOK {
	return &AssetsDeleteOK{}
}

/* AssetsDeleteOK describes a response with status code 200, with default header values.

AssetsDeleteOK assets delete o k
*/
type AssetsDeleteOK struct {
}

func (o *AssetsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /assets/{id}/][%d] assetsDeleteOK ", 200)
}

func (o *AssetsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewAssetsDeleteUnauthorized creates a AssetsDeleteUnauthorized with default headers values
func NewAssetsDeleteUnauthorized() *AssetsDeleteUnauthorized {
	return &AssetsDeleteUnauthorized{}
}

/* AssetsDeleteUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type AssetsDeleteUnauthorized struct {
}

func (o *AssetsDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /assets/{id}/][%d] assetsDeleteUnauthorized ", 401)
}

func (o *AssetsDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
