// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// GroupsReadReader is a Reader for the GroupsRead structure.
type GroupsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGroupsReadUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGroupsReadOK creates a GroupsReadOK with default headers values
func NewGroupsReadOK() *GroupsReadOK {
	return &GroupsReadOK{}
}

/* GroupsReadOK describes a response with status code 200, with default header values.

GroupsReadOK groups read o k
*/
type GroupsReadOK struct {
	Payload *models.GroupRead
}

func (o *GroupsReadOK) Error() string {
	return fmt.Sprintf("[GET /groups/{id}/][%d] groupsReadOK  %+v", 200, o.Payload)
}
func (o *GroupsReadOK) GetPayload() *models.GroupRead {
	return o.Payload
}

func (o *GroupsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupRead)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupsReadUnauthorized creates a GroupsReadUnauthorized with default headers values
func NewGroupsReadUnauthorized() *GroupsReadUnauthorized {
	return &GroupsReadUnauthorized{}
}

/* GroupsReadUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type GroupsReadUnauthorized struct {
}

func (o *GroupsReadUnauthorized) Error() string {
	return fmt.Sprintf("[GET /groups/{id}/][%d] groupsReadUnauthorized ", 401)
}

func (o *GroupsReadUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
