// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GroupsDeleteReader is a Reader for the GroupsDelete structure.
type GroupsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupsDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGroupsDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGroupsDeleteOK creates a GroupsDeleteOK with default headers values
func NewGroupsDeleteOK() *GroupsDeleteOK {
	return &GroupsDeleteOK{}
}

/* GroupsDeleteOK describes a response with status code 200, with default header values.

GroupsDeleteOK groups delete o k
*/
type GroupsDeleteOK struct {
}

func (o *GroupsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /groups/{id}/][%d] groupsDeleteOK ", 200)
}

func (o *GroupsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGroupsDeleteUnauthorized creates a GroupsDeleteUnauthorized with default headers values
func NewGroupsDeleteUnauthorized() *GroupsDeleteUnauthorized {
	return &GroupsDeleteUnauthorized{}
}

/* GroupsDeleteUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type GroupsDeleteUnauthorized struct {
}

func (o *GroupsDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /groups/{id}/][%d] groupsDeleteUnauthorized ", 401)
}

func (o *GroupsDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
