// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGroupsDeleteParams creates a new GroupsDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGroupsDeleteParams() *GroupsDeleteParams {
	return &GroupsDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGroupsDeleteParamsWithTimeout creates a new GroupsDeleteParams object
// with the ability to set a timeout on a request.
func NewGroupsDeleteParamsWithTimeout(timeout time.Duration) *GroupsDeleteParams {
	return &GroupsDeleteParams{
		timeout: timeout,
	}
}

// NewGroupsDeleteParamsWithContext creates a new GroupsDeleteParams object
// with the ability to set a context for a request.
func NewGroupsDeleteParamsWithContext(ctx context.Context) *GroupsDeleteParams {
	return &GroupsDeleteParams{
		Context: ctx,
	}
}

// NewGroupsDeleteParamsWithHTTPClient creates a new GroupsDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewGroupsDeleteParamsWithHTTPClient(client *http.Client) *GroupsDeleteParams {
	return &GroupsDeleteParams{
		HTTPClient: client,
	}
}

/* GroupsDeleteParams contains all the parameters to send to the API endpoint
   for the groups delete operation.

   Typically these are written to a http.Request.
*/
type GroupsDeleteParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the groups delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupsDeleteParams) WithDefaults() *GroupsDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the groups delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupsDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the groups delete params
func (o *GroupsDeleteParams) WithTimeout(timeout time.Duration) *GroupsDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the groups delete params
func (o *GroupsDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the groups delete params
func (o *GroupsDeleteParams) WithContext(ctx context.Context) *GroupsDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the groups delete params
func (o *GroupsDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the groups delete params
func (o *GroupsDeleteParams) WithHTTPClient(client *http.Client) *GroupsDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the groups delete params
func (o *GroupsDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the groups delete params
func (o *GroupsDeleteParams) WithID(id string) *GroupsDeleteParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the groups delete params
func (o *GroupsDeleteParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GroupsDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
