// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGroupsListParams creates a new GroupsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGroupsListParams() *GroupsListParams {
	return &GroupsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGroupsListParamsWithTimeout creates a new GroupsListParams object
// with the ability to set a timeout on a request.
func NewGroupsListParamsWithTimeout(timeout time.Duration) *GroupsListParams {
	return &GroupsListParams{
		timeout: timeout,
	}
}

// NewGroupsListParamsWithContext creates a new GroupsListParams object
// with the ability to set a context for a request.
func NewGroupsListParamsWithContext(ctx context.Context) *GroupsListParams {
	return &GroupsListParams{
		Context: ctx,
	}
}

// NewGroupsListParamsWithHTTPClient creates a new GroupsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewGroupsListParamsWithHTTPClient(client *http.Client) *GroupsListParams {
	return &GroupsListParams{
		HTTPClient: client,
	}
}

/* GroupsListParams contains all the parameters to send to the API endpoint
   for the groups list operation.

   Typically these are written to a http.Request.
*/
type GroupsListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the groups list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupsListParams) WithDefaults() *GroupsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the groups list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the groups list params
func (o *GroupsListParams) WithTimeout(timeout time.Duration) *GroupsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the groups list params
func (o *GroupsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the groups list params
func (o *GroupsListParams) WithContext(ctx context.Context) *GroupsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the groups list params
func (o *GroupsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the groups list params
func (o *GroupsListParams) WithHTTPClient(client *http.Client) *GroupsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the groups list params
func (o *GroupsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *GroupsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
