// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// NewGroupsPartialUpdateParams creates a new GroupsPartialUpdateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGroupsPartialUpdateParams() *GroupsPartialUpdateParams {
	return &GroupsPartialUpdateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGroupsPartialUpdateParamsWithTimeout creates a new GroupsPartialUpdateParams object
// with the ability to set a timeout on a request.
func NewGroupsPartialUpdateParamsWithTimeout(timeout time.Duration) *GroupsPartialUpdateParams {
	return &GroupsPartialUpdateParams{
		timeout: timeout,
	}
}

// NewGroupsPartialUpdateParamsWithContext creates a new GroupsPartialUpdateParams object
// with the ability to set a context for a request.
func NewGroupsPartialUpdateParamsWithContext(ctx context.Context) *GroupsPartialUpdateParams {
	return &GroupsPartialUpdateParams{
		Context: ctx,
	}
}

// NewGroupsPartialUpdateParamsWithHTTPClient creates a new GroupsPartialUpdateParams object
// with the ability to set a custom HTTPClient for a request.
func NewGroupsPartialUpdateParamsWithHTTPClient(client *http.Client) *GroupsPartialUpdateParams {
	return &GroupsPartialUpdateParams{
		HTTPClient: client,
	}
}

/* GroupsPartialUpdateParams contains all the parameters to send to the API endpoint
   for the groups partial update operation.

   Typically these are written to a http.Request.
*/
type GroupsPartialUpdateParams struct {

	// Data.
	Data *models.GroupWrite

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the groups partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupsPartialUpdateParams) WithDefaults() *GroupsPartialUpdateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the groups partial update params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GroupsPartialUpdateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the groups partial update params
func (o *GroupsPartialUpdateParams) WithTimeout(timeout time.Duration) *GroupsPartialUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the groups partial update params
func (o *GroupsPartialUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the groups partial update params
func (o *GroupsPartialUpdateParams) WithContext(ctx context.Context) *GroupsPartialUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the groups partial update params
func (o *GroupsPartialUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the groups partial update params
func (o *GroupsPartialUpdateParams) WithHTTPClient(client *http.Client) *GroupsPartialUpdateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the groups partial update params
func (o *GroupsPartialUpdateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the groups partial update params
func (o *GroupsPartialUpdateParams) WithData(data *models.GroupWrite) *GroupsPartialUpdateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the groups partial update params
func (o *GroupsPartialUpdateParams) SetData(data *models.GroupWrite) {
	o.Data = data
}

// WithID adds the id to the groups partial update params
func (o *GroupsPartialUpdateParams) WithID(id string) *GroupsPartialUpdateParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the groups partial update params
func (o *GroupsPartialUpdateParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *GroupsPartialUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
