// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// GroupsListReader is a Reader for the GroupsList structure.
type GroupsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewGroupsListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGroupsListOK creates a GroupsListOK with default headers values
func NewGroupsListOK() *GroupsListOK {
	return &GroupsListOK{}
}

/* GroupsListOK describes a response with status code 200, with default header values.

GroupsListOK groups list o k
*/
type GroupsListOK struct {
	Payload *models.GroupRead
}

func (o *GroupsListOK) Error() string {
	return fmt.Sprintf("[GET /groups/][%d] groupsListOK  %+v", 200, o.Payload)
}
func (o *GroupsListOK) GetPayload() *models.GroupRead {
	return o.Payload
}

func (o *GroupsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupRead)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupsListUnauthorized creates a GroupsListUnauthorized with default headers values
func NewGroupsListUnauthorized() *GroupsListUnauthorized {
	return &GroupsListUnauthorized{}
}

/* GroupsListUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type GroupsListUnauthorized struct {
}

func (o *GroupsListUnauthorized) Error() string {
	return fmt.Sprintf("[GET /groups/][%d] groupsListUnauthorized ", 401)
}

func (o *GroupsListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
