// Code generated by go-swagger; DO NOT EDIT.

package groups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// GroupsPartialUpdateReader is a Reader for the GroupsPartialUpdate structure.
type GroupsPartialUpdateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GroupsPartialUpdateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGroupsPartialUpdateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGroupsPartialUpdateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGroupsPartialUpdateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewGroupsPartialUpdateOK creates a GroupsPartialUpdateOK with default headers values
func NewGroupsPartialUpdateOK() *GroupsPartialUpdateOK {
	return &GroupsPartialUpdateOK{}
}

/* GroupsPartialUpdateOK describes a response with status code 200, with default header values.

GroupsPartialUpdateOK groups partial update o k
*/
type GroupsPartialUpdateOK struct {
	Payload *models.GroupRead
}

func (o *GroupsPartialUpdateOK) Error() string {
	return fmt.Sprintf("[PATCH /groups/{id}/][%d] groupsPartialUpdateOK  %+v", 200, o.Payload)
}
func (o *GroupsPartialUpdateOK) GetPayload() *models.GroupRead {
	return o.Payload
}

func (o *GroupsPartialUpdateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GroupRead)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGroupsPartialUpdateBadRequest creates a GroupsPartialUpdateBadRequest with default headers values
func NewGroupsPartialUpdateBadRequest() *GroupsPartialUpdateBadRequest {
	return &GroupsPartialUpdateBadRequest{}
}

/* GroupsPartialUpdateBadRequest describes a response with status code 400, with default header values.

You sent a malformed or bad request.
*/
type GroupsPartialUpdateBadRequest struct {
}

func (o *GroupsPartialUpdateBadRequest) Error() string {
	return fmt.Sprintf("[PATCH /groups/{id}/][%d] groupsPartialUpdateBadRequest ", 400)
}

func (o *GroupsPartialUpdateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewGroupsPartialUpdateUnauthorized creates a GroupsPartialUpdateUnauthorized with default headers values
func NewGroupsPartialUpdateUnauthorized() *GroupsPartialUpdateUnauthorized {
	return &GroupsPartialUpdateUnauthorized{}
}

/* GroupsPartialUpdateUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type GroupsPartialUpdateUnauthorized struct {
}

func (o *GroupsPartialUpdateUnauthorized) Error() string {
	return fmt.Sprintf("[PATCH /groups/{id}/][%d] groupsPartialUpdateUnauthorized ", 401)
}

func (o *GroupsPartialUpdateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
