// Code generated by go-swagger; DO NOT EDIT.

package playlists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// PlaylistsCreateReader is a Reader for the PlaylistsCreate structure.
type PlaylistsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaylistsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewPlaylistsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewPlaylistsCreateBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewPlaylistsCreateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPlaylistsCreateCreated creates a PlaylistsCreateCreated with default headers values
func NewPlaylistsCreateCreated() *PlaylistsCreateCreated {
	return &PlaylistsCreateCreated{}
}

/* PlaylistsCreateCreated describes a response with status code 201, with default header values.

PlaylistsCreateCreated playlists create created
*/
type PlaylistsCreateCreated struct {
	Payload *models.PlaylistRead
}

func (o *PlaylistsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /playlists/][%d] playlistsCreateCreated  %+v", 201, o.Payload)
}
func (o *PlaylistsCreateCreated) GetPayload() *models.PlaylistRead {
	return o.Payload
}

func (o *PlaylistsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PlaylistRead)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPlaylistsCreateBadRequest creates a PlaylistsCreateBadRequest with default headers values
func NewPlaylistsCreateBadRequest() *PlaylistsCreateBadRequest {
	return &PlaylistsCreateBadRequest{}
}

/* PlaylistsCreateBadRequest describes a response with status code 400, with default header values.

You sent a malformed or bad request.
*/
type PlaylistsCreateBadRequest struct {
}

func (o *PlaylistsCreateBadRequest) Error() string {
	return fmt.Sprintf("[POST /playlists/][%d] playlistsCreateBadRequest ", 400)
}

func (o *PlaylistsCreateBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPlaylistsCreateUnauthorized creates a PlaylistsCreateUnauthorized with default headers values
func NewPlaylistsCreateUnauthorized() *PlaylistsCreateUnauthorized {
	return &PlaylistsCreateUnauthorized{}
}

/* PlaylistsCreateUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type PlaylistsCreateUnauthorized struct {
}

func (o *PlaylistsCreateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /playlists/][%d] playlistsCreateUnauthorized ", 401)
}

func (o *PlaylistsCreateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
