// Code generated by go-swagger; DO NOT EDIT.

package playlists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// PlaylistsListReader is a Reader for the PlaylistsList structure.
type PlaylistsListReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaylistsListReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPlaylistsListOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPlaylistsListUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPlaylistsListOK creates a PlaylistsListOK with default headers values
func NewPlaylistsListOK() *PlaylistsListOK {
	return &PlaylistsListOK{}
}

/* PlaylistsListOK describes a response with status code 200, with default header values.

PlaylistsListOK playlists list o k
*/
type PlaylistsListOK struct {
	Payload *models.PlaylistListRead
}

func (o *PlaylistsListOK) Error() string {
	return fmt.Sprintf("[GET /playlists/][%d] playlistsListOK  %+v", 200, o.Payload)
}
func (o *PlaylistsListOK) GetPayload() *models.PlaylistListRead {
	return o.Payload
}

func (o *PlaylistsListOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PlaylistListRead)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPlaylistsListUnauthorized creates a PlaylistsListUnauthorized with default headers values
func NewPlaylistsListUnauthorized() *PlaylistsListUnauthorized {
	return &PlaylistsListUnauthorized{}
}

/* PlaylistsListUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type PlaylistsListUnauthorized struct {
}

func (o *PlaylistsListUnauthorized) Error() string {
	return fmt.Sprintf("[GET /playlists/][%d] playlistsListUnauthorized ", 401)
}

func (o *PlaylistsListUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
