// Code generated by go-swagger; DO NOT EDIT.

package playlists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPlaylistsListParams creates a new PlaylistsListParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPlaylistsListParams() *PlaylistsListParams {
	return &PlaylistsListParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPlaylistsListParamsWithTimeout creates a new PlaylistsListParams object
// with the ability to set a timeout on a request.
func NewPlaylistsListParamsWithTimeout(timeout time.Duration) *PlaylistsListParams {
	return &PlaylistsListParams{
		timeout: timeout,
	}
}

// NewPlaylistsListParamsWithContext creates a new PlaylistsListParams object
// with the ability to set a context for a request.
func NewPlaylistsListParamsWithContext(ctx context.Context) *PlaylistsListParams {
	return &PlaylistsListParams{
		Context: ctx,
	}
}

// NewPlaylistsListParamsWithHTTPClient creates a new PlaylistsListParams object
// with the ability to set a custom HTTPClient for a request.
func NewPlaylistsListParamsWithHTTPClient(client *http.Client) *PlaylistsListParams {
	return &PlaylistsListParams{
		HTTPClient: client,
	}
}

/* PlaylistsListParams contains all the parameters to send to the API endpoint
   for the playlists list operation.

   Typically these are written to a http.Request.
*/
type PlaylistsListParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the playlists list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PlaylistsListParams) WithDefaults() *PlaylistsListParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the playlists list params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PlaylistsListParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the playlists list params
func (o *PlaylistsListParams) WithTimeout(timeout time.Duration) *PlaylistsListParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the playlists list params
func (o *PlaylistsListParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the playlists list params
func (o *PlaylistsListParams) WithContext(ctx context.Context) *PlaylistsListParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the playlists list params
func (o *PlaylistsListParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the playlists list params
func (o *PlaylistsListParams) WithHTTPClient(client *http.Client) *PlaylistsListParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the playlists list params
func (o *PlaylistsListParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *PlaylistsListParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
