// Code generated by go-swagger; DO NOT EDIT.

package playlists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewPlaylistsReadParams creates a new PlaylistsReadParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPlaylistsReadParams() *PlaylistsReadParams {
	return &PlaylistsReadParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPlaylistsReadParamsWithTimeout creates a new PlaylistsReadParams object
// with the ability to set a timeout on a request.
func NewPlaylistsReadParamsWithTimeout(timeout time.Duration) *PlaylistsReadParams {
	return &PlaylistsReadParams{
		timeout: timeout,
	}
}

// NewPlaylistsReadParamsWithContext creates a new PlaylistsReadParams object
// with the ability to set a context for a request.
func NewPlaylistsReadParamsWithContext(ctx context.Context) *PlaylistsReadParams {
	return &PlaylistsReadParams{
		Context: ctx,
	}
}

// NewPlaylistsReadParamsWithHTTPClient creates a new PlaylistsReadParams object
// with the ability to set a custom HTTPClient for a request.
func NewPlaylistsReadParamsWithHTTPClient(client *http.Client) *PlaylistsReadParams {
	return &PlaylistsReadParams{
		HTTPClient: client,
	}
}

/* PlaylistsReadParams contains all the parameters to send to the API endpoint
   for the playlists read operation.

   Typically these are written to a http.Request.
*/
type PlaylistsReadParams struct {

	// ID.
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the playlists read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PlaylistsReadParams) WithDefaults() *PlaylistsReadParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the playlists read params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PlaylistsReadParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the playlists read params
func (o *PlaylistsReadParams) WithTimeout(timeout time.Duration) *PlaylistsReadParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the playlists read params
func (o *PlaylistsReadParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the playlists read params
func (o *PlaylistsReadParams) WithContext(ctx context.Context) *PlaylistsReadParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the playlists read params
func (o *PlaylistsReadParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the playlists read params
func (o *PlaylistsReadParams) WithHTTPClient(client *http.Client) *PlaylistsReadParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the playlists read params
func (o *PlaylistsReadParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the playlists read params
func (o *PlaylistsReadParams) WithID(id string) *PlaylistsReadParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the playlists read params
func (o *PlaylistsReadParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PlaylistsReadParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
