// Code generated by go-swagger; DO NOT EDIT.

package playlists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// PlaylistsDeleteReader is a Reader for the PlaylistsDelete structure.
type PlaylistsDeleteReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaylistsDeleteReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPlaylistsDeleteOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPlaylistsDeleteUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPlaylistsDeleteOK creates a PlaylistsDeleteOK with default headers values
func NewPlaylistsDeleteOK() *PlaylistsDeleteOK {
	return &PlaylistsDeleteOK{}
}

/* PlaylistsDeleteOK describes a response with status code 200, with default header values.

PlaylistsDeleteOK playlists delete o k
*/
type PlaylistsDeleteOK struct {
}

func (o *PlaylistsDeleteOK) Error() string {
	return fmt.Sprintf("[DELETE /playlists/{id}/][%d] playlistsDeleteOK ", 200)
}

func (o *PlaylistsDeleteOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewPlaylistsDeleteUnauthorized creates a PlaylistsDeleteUnauthorized with default headers values
func NewPlaylistsDeleteUnauthorized() *PlaylistsDeleteUnauthorized {
	return &PlaylistsDeleteUnauthorized{}
}

/* PlaylistsDeleteUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type PlaylistsDeleteUnauthorized struct {
}

func (o *PlaylistsDeleteUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /playlists/{id}/][%d] playlistsDeleteUnauthorized ", 401)
}

func (o *PlaylistsDeleteUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
