// Code generated by go-swagger; DO NOT EDIT.

package playlists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// PlaylistsReadReader is a Reader for the PlaylistsRead structure.
type PlaylistsReadReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PlaylistsReadReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPlaylistsReadOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewPlaylistsReadUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewPlaylistsReadOK creates a PlaylistsReadOK with default headers values
func NewPlaylistsReadOK() *PlaylistsReadOK {
	return &PlaylistsReadOK{}
}

/* PlaylistsReadOK describes a response with status code 200, with default header values.

PlaylistsReadOK playlists read o k
*/
type PlaylistsReadOK struct {
	Payload *models.PlaylistRead
}

func (o *PlaylistsReadOK) Error() string {
	return fmt.Sprintf("[GET /playlists/{id}/][%d] playlistsReadOK  %+v", 200, o.Payload)
}
func (o *PlaylistsReadOK) GetPayload() *models.PlaylistRead {
	return o.Payload
}

func (o *PlaylistsReadOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PlaylistRead)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPlaylistsReadUnauthorized creates a PlaylistsReadUnauthorized with default headers values
func NewPlaylistsReadUnauthorized() *PlaylistsReadUnauthorized {
	return &PlaylistsReadUnauthorized{}
}

/* PlaylistsReadUnauthorized describes a response with status code 401, with default header values.

You provided invalid credentials.
*/
type PlaylistsReadUnauthorized struct {
}

func (o *PlaylistsReadUnauthorized) Error() string {
	return fmt.Sprintf("[GET /playlists/{id}/][%d] playlistsReadUnauthorized ", 401)
}

func (o *PlaylistsReadUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
