// Code generated by go-swagger; DO NOT EDIT.

package playlists

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/phpfs/go-screenly/screenly/models"
)

// NewPlaylistsCreateParams creates a new PlaylistsCreateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPlaylistsCreateParams() *PlaylistsCreateParams {
	return &PlaylistsCreateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPlaylistsCreateParamsWithTimeout creates a new PlaylistsCreateParams object
// with the ability to set a timeout on a request.
func NewPlaylistsCreateParamsWithTimeout(timeout time.Duration) *PlaylistsCreateParams {
	return &PlaylistsCreateParams{
		timeout: timeout,
	}
}

// NewPlaylistsCreateParamsWithContext creates a new PlaylistsCreateParams object
// with the ability to set a context for a request.
func NewPlaylistsCreateParamsWithContext(ctx context.Context) *PlaylistsCreateParams {
	return &PlaylistsCreateParams{
		Context: ctx,
	}
}

// NewPlaylistsCreateParamsWithHTTPClient creates a new PlaylistsCreateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPlaylistsCreateParamsWithHTTPClient(client *http.Client) *PlaylistsCreateParams {
	return &PlaylistsCreateParams{
		HTTPClient: client,
	}
}

/* PlaylistsCreateParams contains all the parameters to send to the API endpoint
   for the playlists create operation.

   Typically these are written to a http.Request.
*/
type PlaylistsCreateParams struct {

	// Data.
	Data *models.PlaylistWrite

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the playlists create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PlaylistsCreateParams) WithDefaults() *PlaylistsCreateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the playlists create params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PlaylistsCreateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the playlists create params
func (o *PlaylistsCreateParams) WithTimeout(timeout time.Duration) *PlaylistsCreateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the playlists create params
func (o *PlaylistsCreateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the playlists create params
func (o *PlaylistsCreateParams) WithContext(ctx context.Context) *PlaylistsCreateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the playlists create params
func (o *PlaylistsCreateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the playlists create params
func (o *PlaylistsCreateParams) WithHTTPClient(client *http.Client) *PlaylistsCreateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the playlists create params
func (o *PlaylistsCreateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithData adds the data to the playlists create params
func (o *PlaylistsCreateParams) WithData(data *models.PlaylistWrite) *PlaylistsCreateParams {
	o.SetData(data)
	return o
}

// SetData adds the data to the playlists create params
func (o *PlaylistsCreateParams) SetData(data *models.PlaylistWrite) {
	o.Data = data
}

// WriteToRequest writes these params to a swagger request
func (o *PlaylistsCreateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Data != nil {
		if err := r.SetBodyParam(o.Data); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
